name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Foreman
        run: |
          curl -L https://github.com/Roblox/foreman/releases/latest/download/foreman-linux -o foreman
          chmod +x foreman
          sudo mv foreman /usr/local/bin/

      - name: Install tools
        run: foreman install

      - name: Install Wally packages
        run: wally install

      - name: Build place
        run: rojo build test.project.json -o test.rbxl